-- Baseline schema for MovieUniverse Hub.
-- Shaped by data/seed_playlists.json: the unusual constraints below exist
-- because the provided seed data would otherwise fail to import.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- tmdb_id is the natural key: the seed holds two films called Dune (841, 438631)
-- and two called The Lion King (8587, 420818), so title is never an identifier.
-- fetched_at IS NULL marks a stub row, letting the importer satisfy foreign keys
-- before it has talked to TMDB.
CREATE TABLE movie (
    tmdb_id            BIGINT PRIMARY KEY,
    title              TEXT,
    original_title     TEXT,
    release_date       DATE,
    overview           TEXT,
    poster_path        TEXT,
    runtime            INTEGER,
    -- (5, 3) not (4, 3): a film with one or two perfect votes averages a clean
    -- 10.0, which overflows four digits of precision.
    tmdb_vote_average  NUMERIC(5, 3),
    tmdb_vote_count    INTEGER     NOT NULL DEFAULT 0,
    fetched_at         TIMESTAMPTZ,
    -- TMDB sends 0.0 rather than null for an unvoted film. The briefing requires
    -- "sem votos" instead of "0", so the absence of votes is stored as NULL here
    -- and the rule lives in the database, not only in the UI.
    -- Written as an equivalence on purpose: "count = 0 OR average IS NOT NULL"
    -- looks right but is satisfied by its first branch, so it would still accept
    -- the 0.0 that TMDB actually sends.
    CONSTRAINT vote_average_null_exactly_when_no_votes
        CHECK ((tmdb_vote_count = 0) = (tmdb_vote_average IS NULL)),
    CONSTRAINT vote_count_not_negative CHECK (tmdb_vote_count >= 0)
);

CREATE TABLE genre (
    id   BIGINT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE movie_genre (
    tmdb_id  BIGINT NOT NULL REFERENCES movie (tmdb_id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genre (id)      ON DELETE CASCADE,
    PRIMARY KEY (tmdb_id, genre_id)
);

-- external_id holds "pl-01" for seeded playlists and stays NULL for ones created
-- in the app; it is the key that makes a second import a no-op.
-- deleted_at is the soft delete behind "apagada": true.
CREATE TABLE playlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(50) UNIQUE,
    name        VARCHAR(120) NOT NULL,
    owner_id    BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_playlist_owner_active ON playlist (owner_id) WHERE deleted_at IS NULL;

-- Surrogate primary key, deliberately NOT unique on (playlist_id, tmdb_id):
-- pl-01 contains tmdb_id 27205 at both ordem 1 and ordem 6.
CREATE TABLE playlist_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT  NOT NULL REFERENCES playlist (id) ON DELETE CASCADE,
    tmdb_id     BIGINT  NOT NULL REFERENCES movie (tmdb_id),
    position    INTEGER NOT NULL,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT position_is_positive CHECK (position > 0),
    -- Deferred so a reorder can rewrite every position inside one transaction
    -- without colliding on intermediate states.
    CONSTRAINT uq_playlist_item_position UNIQUE (playlist_id, position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_playlist_item_playlist ON playlist_item (playlist_id);
CREATE INDEX idx_playlist_item_movie    ON playlist_item (tmdb_id);

-- One rating per user per film: enforces the briefing rule and doubles as the
-- upsert key that keeps the import idempotent.
CREATE TABLE user_rating (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    tmdb_id    BIGINT   NOT NULL REFERENCES movie (tmdb_id),
    stars      SMALLINT NOT NULL,
    rated_at   DATE     NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT stars_within_range CHECK (stars BETWEEN 1 AND 10),
    CONSTRAINT uq_user_rating_user_movie UNIQUE (user_id, tmdb_id)
);

CREATE INDEX idx_user_rating_movie ON user_rating (tmdb_id);

CREATE TABLE game_score (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT  NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    score     INTEGER NOT NULL,
    played_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT score_not_negative CHECK (score >= 0)
);

CREATE INDEX idx_game_score_leaderboard ON game_score (score DESC, played_at);
